#!/bin/bash
# Build all harleycameron-rgb packages for Zenodo archival
# This script clones repositories, builds distributions, and packages them

set -e

# Configuration
GITHUB_USER="harleycameron-rgb"
WORK_DIR="./package-build"
OUTPUT_DIR="./zenodo-packages"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
ARCHIVE_NAME="harleycameron-packages_${TIMESTAMP}.tar.gz"

# Repositories to package
declare -a REPOS=(
    "sentinel_dot"
    "scandoc-provenance"
    "bounded-mdl-residue-test"
    "convergence-sim"
    "blueprint-invariant-overlay"
)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Building Packages for Zenodo ===${NC}\n"

# Create working directories
mkdir -p "$WORK_DIR"
mkdir -p "$OUTPUT_DIR"

# Function to build a single package
build_package() {
    local repo=$1
    local repo_dir="$WORK_DIR/$repo"
    
    echo -e "${BLUE}→ Processing: $repo${NC}"
    
    # Clone repository
    if [ -d "$repo_dir" ]; then
        echo "  (already cloned, pulling latest)"
        cd "$repo_dir"
        git pull
        cd - > /dev/null
    else
        echo "  Cloning from GitHub..."
        git clone "https://github.com/$GITHUB_USER/$repo.git" "$repo_dir" --depth 1
    fi
    
    # Build distributions
    cd "$repo_dir"
    
    if [ -f "pyproject.toml" ] || [ -f "setup.py" ]; then
        echo "  Building distributions..."
        
        # Clean previous builds
        rm -rf build dist *.egg-info
        
        # Install build tool if needed
        python3 -m pip install build -q 2>/dev/null || true
        
        # Build
        python3 -m build --outdir "$OUTPUT_DIR" 2>&1 | grep -E "(dist|error|warning)" || true
        
        echo -e "  ${GREEN}✓ Built successfully${NC}"
    else
        echo -e "  ${RED}✗ No pyproject.toml or setup.py found${NC}"
    fi
    
    cd - > /dev/null
}

# Build all packages
for repo in "${REPOS[@]}"; do
    build_package "$repo"
    echo ""
done

# Create summary
echo -e "${BLUE}=== Build Summary ===${NC}\n"

# Count distributions
declare -A package_counts
cd "$OUTPUT_DIR"

for repo in "${REPOS[@]}"; do
    count=$(ls -1 ${repo}* 2>/dev/null | wc -l)
    if [ $count -gt 0 ]; then
        echo -e "${GREEN}✓ $repo: $count file(s)${NC}"
        package_counts[$repo]=$count
    else
        echo -e "${RED}✗ $repo: no distributions found${NC}"
    fi
done

# Create archive
echo ""
echo -e "${BLUE}Creating archive: $ARCHIVE_NAME${NC}"
tar -czf "$ARCHIVE_NAME" --exclude='*.git*' --exclude='__pycache__' --exclude='*.egg-info' .

ARCHIVE_SIZE=$(du -h "$ARCHIVE_NAME" | cut -f1)
echo -e "${GREEN}✓ Archive created: $ARCHIVE_SIZE${NC}\n"

# Create metadata file
cat > "ZENODO_MANIFEST.txt" << 'EOF'
ZENODO ARCHIVE MANIFEST
=======================
Generated by build-packages.sh

Contents:
- Source distributions (.tar.gz)
- Wheel distributions (.whl)
- For packages by harleycameron-rgb

Packages Included:
1. sentinel_dot - Tamper-evident action logs for AI agents
2. bookprov - Provenance-preserving ingest of printed books
3. mdl-residue-llm - Deterministic MDL residue benchmark for LLM
4. convergence-gate - Experimental regime-change gate over verified logs
5. blueprint-invariant-overlay - Visualization overlay tool

Installation:
Each wheel (.whl) can be installed with:
  pip install <package>.whl

Or from source:
  tar -xzf <package>.tar.gz
  cd <package>
  pip install .

Zenodo Upload:
1. Go to https://zenodo.org/deposit
2. Create new deposition
3. Upload all files from this archive
4. Add metadata for each package
5. Publish

For details, see individual package READMEs.
EOF

echo -e "${BLUE}=== Manifest Created ===${NC}"
cat "ZENODO_MANIFEST.txt"

cd - > /dev/null

echo -e "\n${GREEN}✓ All packages built successfully!${NC}"
echo -e "${BLUE}Output directory: $OUTPUT_DIR${NC}"
echo -e "${BLUE}Archive: $OUTPUT_DIR/$ARCHIVE_NAME${NC}\n"
echo "Next steps:"
echo "1. Review packages in: $OUTPUT_DIR"
echo "2. Upload to Zenodo: https://zenodo.org/deposit"
echo "3. Use ZENODO_MANIFEST.txt as guide"
